new_modules = '''
  "graph": {
    header: "std/graph/graph.h",
    functions: {
      "graph_add_edge": {"args":["Graph*", "const char*", "const char*", "i64"]},
      "graph_add_node": {"args":["Graph*", "const char*", "void*"], "return":"GraphNode*"},
      "graph_bellman_ford": {"args":["const Graph*", "const char*", "i64*"], "return":"bool_t"},
      "graph_bfs": {"args":["const Graph*", "const char*", "void (*)(const GraphNode*, i64, void*)", "void*"]},
      "graph_create": {"args":["bool_t"], "return":"Graph*"},
      "graph_destroy": {"args":["Graph*"]},
      "graph_dfs": {"args":["const Graph*", "const char*", "void (*)(const GraphNode*, i64, void*)", "void*"]},
      "graph_dijkstra": {"args":["const Graph*", "const char*", "const char*"], "return":"i64*"},
      "graph_find_node": {"args":["const Graph*", "const char*"], "return":"GraphNode*"},
      "graph_get_edge_weight": {"args":["const Graph*", "const char*", "const char*"], "return":"i64"},
      "graph_has_cycle": {"args":["const Graph*"], "return":"bool_t"},
      "graph_has_edge": {"args":["const Graph*", "const char*", "const char*"], "return":"bool_t"},
      "graph_in_degree": {"args":["const Graph*", "const char*"], "return":"size_t"},
      "graph_out_degree": {"args":["const Graph*", "const char*"], "return":"size_t"},
      "graph_remove_edge": {"args":["Graph*", "const char*", "const char*"]},
      "graph_strongly_connected_components": {"args":["const Graph*", "GraphNode***", "size_t*"], "return":"size_t"},
      "graph_topological_sort": {"args":["const Graph*", "GraphNode***", "size_t*"]},
    },
  },
  "heap": {
    header: "std/heap/heap.h",
    functions: {
      "heap_build": {"args":["void**", "size_t", "size_t", "int (*)(const void*, const void*)"]},
      "heap_compare_float": {"args":["const void*", "const void*"], "return":"int"},
      "heap_compare_int": {"args":["const void*", "const void*"], "return":"int"},
      "heap_compare_int_desc": {"args":["const void*", "const void*"], "return":"int"},
      "heap_create": {"args":["int (*)(const void*, const void*)"], "return":"Heap*"},
      "heap_decrease_key": {"args":["Heap*", "size_t", "void*"]},
      "heap_destroy": {"args":["Heap*"]},
      "heap_increase_key": {"args":["Heap*", "size_t", "void*"]},
      "heap_is_empty": {"args":["const Heap*"], "return":"bool_t"},
      "heap_merge": {"args":["Heap*", "const Heap*"]},
      "heap_merge_k": {"args":["Heap**", "size_t"], "return":"Heap*"},
      "heap_peek": {"args":["const Heap*"], "return":"void*"},
      "heap_pop": {"args":["Heap*"], "return":"void*"},
      "heap_push": {"args":["Heap*", "void*"]},
      "heap_size": {"args":["const Heap*"], "return":"size_t"},
      "heap_sort": {"args":["void**", "size_t", "size_t", "int (*)(const void*, const void*)"]},
    },
  },
  "trie": {
    header: "std/trie/trie.h",
    functions: {
      "trie_clear": {"args":["Trie*"]},
      "trie_contains": {"args":["const Trie*", "const char*"], "return":"bool_t"},
      "trie_create": {"args":[], "return":"Trie*"},
      "trie_delete": {"args":["Trie*", "const char*"], "return":"bool_t"},
      "trie_destroy": {"args":["Trie*"]},
      "trie_has_prefix": {"args":["const Trie*", "const char*"], "return":"bool_t"},
      "trie_insert": {"args":["Trie*", "const char*", "void*"]},
      "trie_is_empty": {"args":["const Trie*"], "return":"bool_t"},
      "trie_prefix_search": {"args":["const Trie*", "const char*", "void (*)(const char*, void*, void*)", "void*"]},
      "trie_search": {"args":["const Trie*", "const char*"], "return":"void*"},
      "trie_size": {"args":["const Trie*"], "return":"size_t"},
      "trie_traverse": {"args":["const Trie*", "void (*)(const char*, void*, void*)", "void*"]},
    },
  },
  "datetime": {
    header: "std/datetime/datetime.h",
    functions: {
      "datetime_add": {"args":["const DateTime*", "const Duration*"], "return":"DateTime"},
      "datetime_day_of_week": {"args":["const DateTime*"], "return":"i64"},
      "datetime_day_of_year": {"args":["const DateTime*"], "return":"i64"},
      "datetime_diff": {"args":["const DateTime*", "const DateTime*"], "return":"Duration"},
      "datetime_equal": {"args":["const DateTime*", "const DateTime*"], "return":"bool_t"},
      "datetime_from_iso8601": {"args":["const char*"], "return":"DateTime"},
      "datetime_from_string": {"args":["const char*", "const char*"], "return":"DateTime"},
      "datetime_from_timestamp": {"args":["i64"], "return":"DateTime"},
      "datetime_from_timestamp_ns": {"args":["i64"], "return":"DateTime"},
      "datetime_greater": {"args":["const DateTime*", "const DateTime*"], "return":"bool_t"},
      "datetime_is_valid": {"args":["const DateTime*"], "return":"bool_t"},
      "datetime_less": {"args":["const DateTime*", "const DateTime*"], "return":"bool_t"},
      "datetime_now": {"args":[], "return":"DateTime"},
      "datetime_now_utc": {"args":[], "return":"DateTime"},
      "datetime_subtract": {"args":["const DateTime*", "const Duration*"], "return":"DateTime"},
      "datetime_to_iso8601": {"args":["const DateTime*"], "return":"String"},
      "datetime_to_string": {"args":["const DateTime*", "const char*"], "return":"String"},
      "datetime_to_timestamp": {"args":["const DateTime*"], "return":"i64"},
      "datetime_to_timestamp_ns": {"args":["const DateTime*"], "return":"i64"},
      "datetime_to_utc": {"args":["const DateTime*", "const TimeZone*"], "return":"DateTime"},
      "datetime_week_of_year": {"args":["const DateTime*"], "return":"i64"},
      "datetime_with_timezone": {"args":["const DateTime*", "const TimeZone*"], "return":"DateTime"},
      "duration_add": {"args":["const Duration*", "const Duration*"], "return":"Duration"},
      "duration_create": {"args":["i64", "i64", "i64", "i64", "i64"], "return":"Duration"},
      "duration_from_nanoseconds": {"args":["i64"], "return":"Duration"},
      "duration_from_seconds": {"args":["f64"], "return":"Duration"},
      "duration_subtract": {"args":["const Duration*", "const Duration*"], "return":"Duration"},
      "duration_to_nanoseconds": {"args":["const Duration*"], "return":"i64"},
      "duration_to_seconds": {"args":["const Duration*"], "return":"f64"},
      "timezone_create": {"args":["const char*", "i64", "bool_t"], "return":"TimeZone*"},
      "timezone_destroy": {"args":["TimeZone*"]},
      "timezone_local": {"args":[], "return":"TimeZone*"},
      "timezone_utc": {"args":[], "return":"TimeZone*"},
    },
  },
  "calendar": {
    header: "std/calendar/calendar.h",
    functions: {
      "calendar_add_days": {"args":["const Date*", "i64"], "return":"Date"},
      "calendar_create": {"args":["const char*", "i64"], "return":"Calendar*"},
      "calendar_date_equal": {"args":["const Date*", "const Date*"], "return":"bool_t"},
      "calendar_date_greater": {"args":["const Date*", "const Date*"], "return":"bool_t"},
      "calendar_date_less": {"args":["const Date*", "const Date*"], "return":"bool_t"},
      "calendar_day_of_week": {"args":["const Date*"], "return":"i64"},
      "calendar_day_of_year": {"args":["const Date*"], "return":"i64"},
      "calendar_destroy": {"args":["Calendar*"]},
      "calendar_diff_days": {"args":["const Date*", "const Date*"], "return":"i64"},
      "calendar_days_in_month": {"args":["i64", "i64"], "return":"i64"},
      "calendar_days_in_year": {"args":["i64"], "return":"i64"},
      "calendar_first_day_of_month": {"args":["i64", "i64"], "return":"Date"},
      "calendar_first_day_of_week": {"args":["const Date*"], "return":"Date"},
      "calendar_format_date": {"args":["const Date*", "const char*"], "return":"String"},
      "calendar_get_month_info": {"args":["i64"], "return":"MonthInfo"},
      "calendar_get_weekday_info": {"args":["i64"], "return":"WeekdayInfo"},
      "calendar_is_leap_year": {"args":["i64"], "return":"bool_t"},
      "calendar_is_weekend": {"args":["const Date*"], "return":"bool_t"},
      "calendar_is_workday": {"args":["const Date*"], "return":"bool_t"},
      "calendar_last_day_of_month": {"args":["i64", "i64"], "return":"Date"},
      "calendar_last_day_of_week": {"args":["const Date*"], "return":"Date"},
      "calendar_next_workday": {"args":["const Date*"], "return":"Date"},
      "calendar_nth_weekday_in_month": {"args":["i64", "i64", "i64", "i64"], "return":"i64"},
      "calendar_parse_date": {"args":["const char*", "const char*"], "return":"Date"},
      "calendar_previous_workday": {"args":["const Date*"], "return":"Date"},
      "calendar_subtract_days": {"args":["const Date*", "i64"], "return":"Date"},
      "calendar_today": {"args":[], "return":"Date"},
      "calendar_tomorrow": {"args":[], "return":"Date"},
      "calendar_week_of_year": {"args":["const Date*"], "return":"i64"},
      "calendar_weekdays_in_month": {"args":["i64", "i64", "i64"], "return":"i64"},
      "calendar_yesterday": {"args":[], "return":"Date"},
    },
  },
  "protobuf": {
    header: "std/protobuf/protobuf.h",
    functions: {
      "pb_read_bool": {"args":["PBReader*", "bool_t*"], "return":"bool_t"},
      "pb_read_bytes": {"args":["PBReader*", "byte**", "size_t*"], "return":"bool_t"},
      "pb_read_double": {"args":["PBReader*", "f64*"], "return":"bool_t"},
      "pb_read_field": {"args":["PBReader*", "i32*", "i32*"], "return":"bool_t"},
      "pb_read_fixed32": {"args":["PBReader*", "u32*"], "return":"bool_t"},
      "pb_read_fixed64": {"args":["PBReader*", "u64*"], "return":"bool_t"},
      "pb_read_float": {"args":["PBReader*", "f32*"], "return":"bool_t"},
      "pb_read_string": {"args":["PBReader*", "String*"], "return":"bool_t"},
      "pb_read_varint": {"args":["PBReader*", "i64*"], "return":"bool_t"},
      "pb_reader_create": {"args":["const byte*", "size_t"], "return":"PBReader*"},
      "pb_reader_destroy": {"args":["PBReader*"]},
      "pb_skip_field": {"args":["PBReader*", "i32"], "return":"bool_t"},
      "pb_string_size": {"args":["const char*"], "return":"size_t"},
      "pb_varint_size": {"args":["i64"], "return":"size_t"},
      "pb_write_bool": {"args":["PBWriter*", "bool_t"]},
      "pb_write_bytes": {"args":["PBWriter*", "const byte*", "size_t"]},
      "pb_write_double": {"args":["PBWriter*", "f64"]},
      "pb_write_field_fixed32": {"args":["PBWriter*", "i32", "u32"]},
      "pb_write_field_fixed64": {"args":["PBWriter*", "i32", "u64"]},
      "pb_write_field_string": {"args":["PBWriter*", "i32", "const char*"]},
      "pb_write_field_varint": {"args":["PBWriter*", "i32", "i64"]},
      "pb_write_fixed32": {"args":["PBWriter*", "u32"]},
      "pb_write_fixed64": {"args":["PBWriter*", "u64"]},
      "pb_write_float": {"args":["PBWriter*", "f32"]},
      "pb_write_string": {"args":["PBWriter*", "const char*"]},
      "pb_write_varint": {"args":["PBWriter*", "i64"]},
      "pb_writer_create": {"args":[], "return":"PBWriter*"},
      "pb_writer_data": {"args":["const PBWriter*"], "return":"byte*"},
      "pb_writer_destroy": {"args":["PBWriter*"]},
      "pb_writer_reserve": {"args":["PBWriter*", "size_t"]},
    },
  },
  "msgpack": {
    header: "std/msgpack/msgpack.h",
    functions: {
      "mp_read_array_header": {"args":["MPReader*", "size_t*"], "return":"bool_t"},
      "mp_read_bool": {"args":["MPReader*", "bool_t*"], "return":"bool_t"},
      "mp_read_bytes": {"args":["MPReader*", "byte**", "size_t*"], "return":"bool_t"},
      "mp_read_double": {"args":["MPReader*", "f64*"], "return":"bool_t"},
      "mp_read_ext": {"args":["MPReader*", "i8*", "byte**", "size_t*"], "return":"bool_t"},
      "mp_read_float": {"args":["MPReader*", "f32*"], "return":"bool_t"},
      "mp_read_int": {"args":["MPReader*", "i64*"], "return":"bool_t"},
      "mp_read_map_header": {"args":["MPReader*", "size_t*"], "return":"bool_t"},
      "mp_read_nil": {"args":["MPReader*"], "return":"bool_t"},
      "mp_read_string": {"args":["MPReader*", "String*"], "return":"bool_t"},
      "mp_read_type": {"args":["MPReader*"], "return":"MsgPackType"},
      "mp_read_uint": {"args":["MPReader*", "u64*"], "return":"bool_t"},
      "mp_reader_create": {"args":["const byte*", "size_t"], "return":"MPReader*"},
      "mp_reader_destroy": {"args":["MPReader*"]},
      "mp_write_array_header": {"args":["MPWriter*", "size_t"]},
      "mp_write_bool": {"args":["MPWriter*", "bool_t"]},
      "mp_write_bytes": {"args":["MPWriter*", "const byte*", "size_t"]},
      "mp_write_double": {"args":["MPWriter*", "f64"]},
      "mp_write_ext": {"args":["MPWriter*", "i8", "const byte*", "size_t"]},
      "mp_write_float": {"args":["MPWriter*", "f32"]},
      "mp_write_int": {"args":["MPWriter*", "i64"]},
      "mp_write_map_header": {"args":["MPWriter*", "size_t"]},
      "mp_write_nil": {"args":["MPWriter*"]},
      "mp_write_string": {"args":["MPWriter*", "const char*"]},
      "mp_write_uint": {"args":["MPWriter*", "u64"]},
      "mp_writer_create": {"args":[], "return":"MPWriter*"},
      "mp_writer_data": {"args":["const MPWriter*"], "return":"byte*"},
      "mp_writer_destroy": {"args":["MPWriter*"]},
    },
  },
  "parallel": {
    header: "std/parallel/parallel.h",
    functions: {
      "parallel_all_of": {"args":["i64*", "size_t", "bool_t (*)(i64)"], "return":"bool_t"},
      "parallel_any_of": {"args":["i64*", "size_t", "bool_t (*)(i64)"], "return":"bool_t"},
      "parallel_copy": {"args":["void*", "void*", "size_t", "size_t"]},
      "parallel_count_if": {"args":["i64*", "size_t", "bool_t (*)(i64)"], "return":"size_t"},
      "parallel_fill": {"args":["void*", "size_t", "size_t", "const void*"]},
      "parallel_filter": {"args":["i64*", "i64*", "size_t", "size_t*", "bool_t (*)(i64)"]},
      "parallel_find_first": {"args":["i64*", "size_t", "bool_t (*)(i64)"], "return":"i64"},
      "parallel_for": {"args":["size_t", "size_t", "void (*)(void*, size_t)", "void*"]},
      "parallel_for_chunked": {"args":["size_t", "size_t", "size_t", "void (*)(void*, size_t)", "void*"]},
      "parallel_for_each": {"args":["i64*", "size_t", "void (*)(i64*)"]},
      "parallel_get_thread_count": {"args":[], "return":"size_t"},
      "parallel_init": {"args":[]},
      "parallel_map": {"args":["i64*", "i64*", "size_t", "i64 (*)(i64)"]},
      "parallel_none_of": {"args":["i64*", "size_t", "bool_t (*)(i64)"], "return":"bool_t"},
      "parallel_prefix_sum": {"args":["i64*", "size_t"]},
      "parallel_reduce": {"args":["i64*", "size_t", "i64 (*)(i64, i64)", "i64"], "return":"i64"},
      "parallel_scan": {"args":["i64*", "i64*", "size_t", "i64 (*)(i64, i64)", "i64"]},
      "parallel_set_thread_count": {"args":["size_t"]},
      "parallel_shutdown": {"args":[]},
      "parallel_sort": {"args":["i64*", "size_t"]},
      "parallel_sort_with_compare": {"args":["void*", "size_t", "size_t", "int (*)(const void*, const void*)"]},
    },
  },
  "tls": {
    header: "std/tls/tls.h",
    functions: {
      "tls_accept": {"args":["TLSContext*"], "return":"bool_t"},
      "tls_client_create": {"args":["Socket*"], "return":"TLSContext*"},
      "tls_connect": {"args":["TLSContext*", "const char*"], "return":"bool_t"},
      "tls_destroy": {"args":["TLSContext*"]},
      "tls_get_cipher_name": {"args":["TLSContext*"], "return":"String"},
      "tls_get_peer_certificate": {"args":["TLSContext*"], "return":"String"},
      "tls_get_version": {"args":["TLSContext*"], "return":"TLSVersion"},
      "tls_load_ca_certificates": {"args":["TLSContext*", "const char*"], "return":"bool_t"},
      "tls_load_certificate": {"args":["TLSContext*", "const char*", "const char*"], "return":"bool_t"},
      "tls_read": {"args":["TLSContext*", "byte*", "size_t"], "return":"ssize_t"},
      "tls_server_create": {"args":["Socket*"], "return":"TLSContext*"},
      "tls_set_cipher": {"args":["TLSContext*", "TLSCipher"], "return":"bool_t"},
      "tls_set_version": {"args":["TLSContext*", "TLSVersion"], "return":"bool_t"},
      "tls_shutdown": {"args":["TLSContext*"]},
      "tls_verify_certificate": {"args":["TLSContext*"], "return":"bool_t"},
      "tls_write": {"args":["TLSContext*", "const byte*", "size_t"], "return":"ssize_t"},
    },
  },
  "ssh": {
    header: "std/ssh/ssh.h",
    functions: {
      "ssh_authenticate_password": {"args":["SSHSession*", "const char*"], "return":"bool_t"},
      "ssh_authenticate_public_key": {"args":["SSHSession*", "const char*"], "return":"bool_t"},
      "ssh_channel_close": {"args":["SSHChannel*"]},
      "ssh_channel_destroy": {"args":["SSHChannel*"]},
      "ssh_channel_open_sftp": {"args":["SSHSession*"], "return":"SSHChannel*"},
      "ssh_channel_open_session": {"args":["SSHSession*"], "return":"SSHChannel*"},
      "ssh_channel_read": {"args":["SSHChannel*", "byte*", "size_t"], "return":"ssize_t"},
      "ssh_channel_request_exec": {"args":["SSHChannel*", "const char*"], "return":"bool_t"},
      "ssh_channel_request_shell": {"args":["SSHChannel*"], "return":"bool_t"},
      "ssh_channel_write": {"args":["SSHChannel*", "const byte*", "size_t"], "return":"ssize_t"},
      "ssh_connect": {"args":["SSHSession*"], "return":"bool_t"},
      "ssh_disconnect": {"args":["SSHSession*"], "return":"bool_t"},
      "ssh_get_host_key": {"args":["SSHSession*"], "return":"String"},
      "ssh_get_server_version": {"args":["SSHSession*"], "return":"String"},
      "ssh_is_connected": {"args":["const SSHSession*"], "return":"bool_t"},
      "ssh_port_forward": {"args":["SSHSession*", "const char*", "i64", "const char*", "i64"], "return":"bool_t"},
      "ssh_session_create": {"args":["const char*", "i64", "const char*", "const char*"], "return":"SSHSession*"},
      "ssh_session_destroy": {"args":["SSHSession*"]},
      "ssh_sftp_get": {"args":["SSHChannel*", "const char*", "const char*"], "return":"bool_t"},
      "ssh_sftp_list_dir": {"args":["SSHChannel*", "const char*"], "return":"bool_t"},
      "ssh_sftp_mkdir": {"args":["SSHChannel*", "const char*"], "return":"bool_t"},
      "ssh_sftp_put": {"args":["SSHChannel*", "const char*", "const char*"], "return":"bool_t"},
      "ssh_sftp_remove": {"args":["SSHChannel*", "const char*"], "return":"bool_t"},
      "ssh_sftp_rmdir": {"args":["SSHChannel*", "const char*"], "return":"bool_t"},
      "ssh_sftp_stat": {"args":["SSHChannel*", "const char*", "void*"], "return":"bool_t"},
    },
  },
'''

import re

filepath = r'c:\Users\28507\Desktop\Kaula_Toolkit\kaula_for_vscode\src\stdlibData.ts'

with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

content = content.rstrip()
if content.endswith('};'):
    content = content[:-2] + new_modules + '};'
else:
    print("Could not find closing '};'")
    exit(1)

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"Successfully updated {filepath} with new modules")
