package stdlib

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

// ClangASTNode 表示 clang -ast-dump=json 输出的 AST 节点
type ClangASTNode struct {
	Kind         string         `json:"kind"`
	Name         string         `json:"name,omitempty"`
	Type         *ClangQualType `json:"type,omitempty"`
	Inner        []ClangASTNode `json:"inner,omitempty"`
	IsImplicit   bool           `json:"isImplicit,omitempty"`
	IsUsed       bool           `json:"isUsed,omitempty"`
	StorageClass string         `json:"storageClass,omitempty"`
	Loc          *ClangLoc      `json:"loc,omitempty"`
	MangledName  string         `json:"mangledName,omitempty"`
}

// ClangQualType 表示 clang AST 中的 qualType 字段
type ClangQualType struct {
	QualType string `json:"qualType"`
}

// ClangLoc 表示 clang AST 中的位置信息
type ClangLoc struct {
	File         string `json:"file,omitempty"`
	Line         int    `json:"line,omitempty"`
	Column       int    `json:"col,omitempty"`
	Offset       int    `json:"offset,omitempty"`
	IncludedFrom *struct {
		File string `json:"file"`
	} `json:"includedFrom,omitempty"`
}

// LibAnalysisResult 表示库分析结果
type LibAnalysisResult struct {
	Name           string
	Type           string   // "single_header" | "multi_header"
	Header         string   // 主头文件
	Headers        []string // 所有需要的头文件
	ImplementMacro string   // 如果需要 XXX_IMPLEMENTATION
	Functions      map[string]Function
	Libraries      []string // 需要链接的库
	IncludePath    string
	LibraryPath    string
	AutoGenerated  bool
	GeneratedAt    string
}

// findClangPath 查找 clang 可执行文件路径
func findClangPath() (string, error) {
	// 尝试直接查找
	if p, err := exec.LookPath("clang"); err == nil {
		return p, nil
	}
	// Windows 常见安装路径
	windowsPaths := []string{
		`D:\LLVM\bin\clang.exe`,
		`C:\LLVM\bin\clang.exe`,
		`C:\Program Files\LLVM\bin\clang.exe`,
	}
	for _, p := range windowsPaths {
		if _, err := os.Stat(p); err == nil {
			return p, nil
		}
	}
	return "", fmt.Errorf("clang not found in PATH or common locations")
}

// classifyLibrary 分类库是单头文件还是多头文件
func classifyLibrary(libDir string) (string, []string, error) {
	var headerFiles []string
	entries, err := os.ReadDir(libDir)
	if err != nil {
		return "", nil, err
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if strings.HasSuffix(name, ".h") || strings.HasSuffix(name, ".hpp") {
			headerFiles = append(headerFiles, name)
		}
	}
	if len(headerFiles) == 0 {
		return "", nil, fmt.Errorf("no header files found in %s", libDir)
	}
	if len(headerFiles) == 1 {
		return "single_header", headerFiles, nil
	}
	return "multi_header", headerFiles, nil
}

// scanLinkLibraries 扫描目录中的链接库文件
func scanLinkLibraries(libDir string) ([]string, string) {
	var libs []string
	var libPath string
	entries, err := os.ReadDir(libDir)
	if err != nil {
		return libs, libPath
	}
	libExts := map[string]bool{".a": true, ".lib": true, ".so": true, ".dll": true, ".dylib": true}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		ext := strings.ToLower(filepath.Ext(name))
		if libExts[ext] {
			// 去掉前缀 lib 和扩展名得到链接名
			base := name
			if strings.HasPrefix(base, "lib") && (ext == ".a" || ext == ".so" || ext == ".dylib") {
				base = base[3:]
			}
			base = strings.TrimSuffix(base, ext)
			// 去掉 .so 后面的版本号后缀
			if idx := strings.Index(base, ".so."); idx >= 0 {
				base = base[:idx]
			}
			libs = append(libs, base)
			libPath = libDir
		}
	}
	return libs, libPath
}

// detectImplementMacro 检测是否需要 XXX_IMPLEMENTATION 宏
func detectImplementMacro(headerContent string, headerName string) string {
	// 常见模式: #ifdef STB_IMAGE_IMPLEMENTATION / #define NK_IMPLEMENTATION
	upperName := strings.ToUpper(strings.TrimSuffix(headerName, filepath.Ext(headerName)))
	// 去掉路径前缀
	if idx := strings.LastIndex(upperName, "/"); idx >= 0 {
		upperName = upperName[idx+1:]
	}
	if idx := strings.LastIndex(upperName, "\\"); idx >= 0 {
		upperName = upperName[idx+1:]
	}
	// 替换非字母数字为下划线
	macroName := ""
	for _, c := range upperName {
		if (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') {
			macroName += string(c)
		} else {
			macroName += "_"
		}
	}
	candidate := macroName + "_IMPLEMENTATION"
	if strings.Contains(headerContent, candidate) {
		return candidate
	}
	return ""
}

// detectCommonMacros 检测常见的导出宏并返回需要预定义的宏
func detectCommonMacros(headerContent string) []string {
	var defines []string
	// 常见导出宏模式
	exportMacros := []struct {
		macro    string
		fallback string
	}{
		{"STBIDEF", "extern"},
		{"NK_API", "extern"},
		{"NK_LIB", "extern"},
		{"ZLIB_API", "extern"},
		{"ZEXPORT", "extern"},
		{"PNG_EXPORT", "extern"},
		{"CURL_EXTERN", "extern"},
		{"SQLITE_API", "extern"},
		{"XMLIMPORT", "extern"},
		{"XMLPARSEAPI", "extern"},
		{"_GLFWAPI", "extern"},
		{"GLAPI", "extern"},
		{"GLEWAPI", "extern"},
		{"SDL_EXPORT", "extern"},
		{"SDL_DECLSPEC", "extern"},
		{"FT_EXPORT", "extern"},
		{"FREETYPE_API", "extern"},
	}
	for _, m := range exportMacros {
		if strings.Contains(headerContent, m.macro) {
			defines = append(defines, fmt.Sprintf("-D%s=%s", m.macro, m.fallback))
		}
	}
	return defines
}

// detectIncludeMacros 检测头文件中的 XXX_INCLUDE_YYY 模式宏并自动启用
// 用于 nuklear 等高度可配置的单头文件库
func detectIncludeMacros(headerContent string) []string {
	var defines []string
	// 使用正则匹配 #ifdef XXX_INCLUDE_YYY 或 #if defined(XXX_INCLUDE_YYY) 模式
	// 提取宏名并自动启用
	seen := make(map[string]bool)

	// 匹配 #ifdef PREFIX_INCLUDE_SUFFIX 模式
	lines := strings.Split(headerContent, "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		// #ifdef MACRO_NAME
		if strings.HasPrefix(line, "#ifdef ") {
			macro := strings.TrimSpace(line[6:])
			if isIncludeMacro(macro) && !seen[macro] {
				seen[macro] = true
				defines = append(defines, "-D"+macro+"=1")
			}
		}
		// #ifndef 模式的反面（不启用）
		// #if defined(MACRO) 模式
		if strings.HasPrefix(line, "#if defined(") {
			// 提取括号内的宏名
			rest := line[len("#if defined("):]
			end := strings.Index(rest, ")")
			if end > 0 {
				macro := strings.TrimSpace(rest[:end])
				if isIncludeMacro(macro) && !seen[macro] {
					seen[macro] = true
					defines = append(defines, "-D"+macro+"=1")
				}
			}
		}
		// # if defined(MACRO) (带空格)
		if strings.HasPrefix(line, "# if defined(") {
			rest := line[len("# if defined("):]
			end := strings.Index(rest, ")")
			if end > 0 {
				macro := strings.TrimSpace(rest[:end])
				if isIncludeMacro(macro) && !seen[macro] {
					seen[macro] = true
					defines = append(defines, "-D"+macro+"=1")
				}
			}
		}
	}

	return defines
}

// isIncludeMacro 判断是否是 INCLUDE 类功能开关宏
func isIncludeMacro(macro string) bool {
	if strings.HasSuffix(macro, "_IMPLEMENTATION") {
		return false
	}
	if strings.Contains(macro, "_INCLUDE_") {
		return true
	}
	featurePatterns := []string{"_ENABLE", "_FEATURE", "_SUPPORT", "_USE_"}
	for _, pattern := range featurePatterns {
		if strings.Contains(macro, pattern) {
			return true
		}
	}
	return false
}

// isSystemFunction 判断是否是系统运行时函数（应跳过）
func isSystemFunction(name string) bool {
	systemPrefixes := []string{
		"__report_",
		"__security_",
		"__init_",
		"__va_",
		"_invalid_parameter_",
		"_invoke_watson",
		"_cexit",
		"_c_exit",
		"_exit",
		"_Exit",
		"_onexit",
		"_beginthread",
		"_endthread",
		"__stdcall",
		"__cdecl",
	}
	for _, prefix := range systemPrefixes {
		if strings.HasPrefix(name, prefix) {
			return true
		}
	}
	return false
}

// extractTypedefs 从 clang AST 中提取所有 typedef 映射
func extractTypedefs(node *ClangASTNode, sourceFile string) map[string]string {
	typedefs := make(map[string]string)
	extractTypedefsRecursive(node, sourceFile, typedefs)
	return typedefs
}

func extractTypedefsRecursive(node *ClangASTNode, sourceFile string, typedefs map[string]string) {
	if node.Kind == "TypedefDecl" && node.Name != "" && node.Type != nil {
		// 跳过隐式 typedef（编译器内部生成的）
		if node.IsImplicit {
			return
		}
		// 只提取来自目标文件或其包含文件的 typedef
		if node.Loc != nil && node.Loc.File != "" {
			locFile := node.Loc.File
			if strings.HasPrefix(locFile, "<") {
				return
			}
			if sourceFile != "" {
				locFileNorm := strings.ReplaceAll(locFile, "\\", "/")
				sourceNorm := strings.ReplaceAll(sourceFile, "\\", "/")
				if !strings.HasPrefix(locFileNorm, sourceNorm) &&
					!strings.Contains(locFileNorm, filepath.Dir(sourceNorm)) {
					return
				}
			}
		}
		typedefs[node.Name] = node.Type.QualType
	}
	for i := range node.Inner {
		extractTypedefsRecursive(&node.Inner[i], sourceFile, typedefs)
	}
}

// expandTypedefs 展开类型字符串中的 typedef 为底层类型
func expandTypedefs(typeStr string, typedefs map[string]string) string {
	result := typeStr
	// 最多迭代 10 次防止循环引用
	for i := 0; i < 10; i++ {
		changed := false
		for name, underlying := range typedefs {
			// 匹配 typedef 名称（作为完整标识符，不是其他类型名的一部分）
			// 模式: 空格或开头 + name + 空格/*/&/(/),/结尾
			newStr := replaceTypeToken(result, name, underlying)
			if newStr != result {
				result = newStr
				changed = true
			}
		}
		if !changed {
			break
		}
	}
	return result
}

// replaceTypeToken 替换类型字符串中的完整类型标识符
func replaceTypeToken(typeStr, oldTok, newTok string) string {
	// 简单实现：按 token 边界替换
	// 在 C 类型中，标识符边界通常是空格、*、&、(、)、,、const、restrict 等
	result := typeStr
	// 直接的子串替换可能导致部分匹配，但在实际库中 typedef 名通常有唯一前缀
	// 使用更精确的边界检查
	var builder strings.Builder
	i := 0
	for i < len(result) {
		// 尝试匹配 oldTok
		if i+len(oldTok) <= len(result) && result[i:i+len(oldTok)] == oldTok {
			// 检查前后是否是类型标识符边界
			beforeOK := (i == 0) || !isIdentChar(result[i-1])
			afterOK := (i+len(oldTok) >= len(result)) || !isIdentChar(result[i+len(oldTok)])
			if beforeOK && afterOK {
				builder.WriteString(newTok)
				i += len(oldTok)
				continue
			}
		}
		builder.WriteByte(result[i])
		i++
	}
	return builder.String()
}

// isIdentChar 检查字符是否是 C 标识符字符
func isIdentChar(c byte) bool {
	return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_'
}

// extractFunctionDecls 从 clang AST JSON 中递归提取函数声明
func extractFunctionDecls(node *ClangASTNode, sourceFile string, typedefs map[string]string) map[string]Function {
	functions := make(map[string]Function)
	extractFunctionDeclsRecursive(node, sourceFile, functions, typedefs)
	return functions
}

func extractFunctionDeclsRecursive(node *ClangASTNode, sourceFile string, functions map[string]Function, typedefs map[string]string) {
	if node.Kind == "FunctionDecl" && node.Name != "" {
		if node.IsImplicit {
			return
		}
		if node.Loc != nil && node.Loc.File != "" {
			locFile := node.Loc.File
			if strings.HasPrefix(locFile, "<") {
				return
			}
			if sourceFile != "" {
				locFileNorm := strings.ReplaceAll(locFile, "\\", "/")
				sourceNorm := strings.ReplaceAll(sourceFile, "\\", "/")
				if !strings.HasPrefix(locFileNorm, sourceNorm) &&
					!strings.Contains(locFileNorm, filepath.Dir(sourceNorm)) &&
					!strings.HasSuffix(locFileNorm, "/"+filepath.Base(sourceNorm)) &&
					!strings.HasSuffix(locFileNorm, "\\"+filepath.Base(sourceNorm)) {
					return
				}
			}
		}

		if isSystemFunction(node.Name) {
			return
		}

		fn := Function{
			Args:   extractParamTypes(node, typedefs),
			Return: extractReturnType(node, typedefs),
		}

		// 检测变参
		if node.Type != nil && strings.Contains(node.Type.QualType, ", ...") {
			fn.VarArgs = true
		}

		functions[node.Name] = fn
	}

	// 递归处理子节点
	for i := range node.Inner {
		extractFunctionDeclsRecursive(&node.Inner[i], sourceFile, functions, typedefs)
	}
}

// extractReturnType 从 FunctionDecl 的 qualType 提取返回类型
func extractReturnType(node *ClangASTNode, typedefs map[string]string) string {
	if node.Type == nil {
		return "void"
	}
	qt := node.Type.QualType
	// 展开 typedef
	qt = expandTypedefs(qt, typedefs)
	// qualType 格式: "return_type (param_types)" 或 "return_type (param_types, ...)"
	idx := findFunctionParen(qt)
	if idx < 0 {
		return normalizeType(qt)
	}
	return normalizeType(strings.TrimSpace(qt[:idx]))
}

// extractParamTypes 从 FunctionDecl 的子节点 ParmVarDecl 提取参数类型
func extractParamTypes(node *ClangASTNode, typedefs map[string]string) []string {
	args := make([]string, 0)
	for i := range node.Inner {
		child := &node.Inner[i]
		if child.Kind == "ParmVarDecl" && child.Type != nil {
			t := child.Type.QualType
			t = expandTypedefs(t, typedefs)
			args = append(args, normalizeType(t))
		}
	}
	return args
}

// findFunctionParen 在 qualType 中找到函数参数的左括号位置
func findFunctionParen(qt string) int {
	depth := 0
	for i, c := range qt {
		if c == '<' {
			depth++
		} else if c == '>' {
			depth--
		} else if c == '(' && depth == 0 {
			return i
		}
	}
	return -1
}

// normalizeType 规范化 C 类型字符串
func normalizeType(typeStr string) string {
	t := strings.TrimSpace(typeStr)
	// 移除多余的空格
	replacements := []struct{ from, to string }{
		{"struct ", ""},
		{"enum ", ""},
		{"class ", ""},
		{"__ptr64", ""},
		{"__cdecl", ""},
		{"__stdcall", ""},
		{"__fastcall", ""},
		{"__thiscall", ""},
		{"__vectorcall", ""},
		{"WINAPI", ""},
		{"CALLBACK", ""},
		{"APIENTRY", ""},
	}
	for _, r := range replacements {
		t = strings.ReplaceAll(t, r.from, r.to)
	}
	// 规范化空格
	for strings.Contains(t, "  ") {
		t = strings.ReplaceAll(t, "  ", " ")
	}
	t = strings.TrimSpace(t)
	// 规范化指针风格: "char *" -> "char*"
	t = strings.ReplaceAll(t, " *", "*")
	t = strings.ReplaceAll(t, " &", "&")
	return t
}

// AnalyzePackage 分析指定包目录，生成配置
func AnalyzePackage(pkgDir string) (*LibAnalysisResult, error) {
	libName := filepath.Base(pkgDir)

	// 1. 分类单/多头文件
	libType, headerFiles, err := classifyLibrary(pkgDir)
	if err != nil {
		return nil, fmt.Errorf("classify library %s: %w", libName, err)
	}

	// 2. 扫描链接库
	libraries, _ := scanLinkLibraries(pkgDir)

	// 3. 读取主头文件内容检测宏
	var mainHeader string
	var headers []string
	if libType == "single_header" && len(headerFiles) == 1 {
		mainHeader = libName + "/" + headerFiles[0]
		headers = []string{fmt.Sprintf(`"%s/%s"`, libName, headerFiles[0])}
	} else {
		// 多头文件：选择与目录同名的头文件为主头文件
		mainHeaderFound := false
		for _, h := range headerFiles {
			baseName := strings.TrimSuffix(h, filepath.Ext(h))
			if baseName == libName {
				mainHeader = libName + "/" + h
				mainHeaderFound = true
				break
			}
		}
		if !mainHeaderFound && len(headerFiles) > 0 {
			mainHeader = libName + "/" + headerFiles[0]
		}
		for _, h := range headerFiles {
			headers = append(headers, fmt.Sprintf(`"%s/%s"`, libName, h))
		}
	}

	// 如果有 libraries 字段，主头文件使用带目录前缀的形式
	if len(libraries) > 0 {
		headers = []string{fmt.Sprintf("\"%s\"", mainHeader)}
	}

	// 4. 读取主头文件内容用于宏检测
	mainHeaderPath := filepath.Join(pkgDir, filepath.Base(mainHeader))
	headerContent, err := os.ReadFile(mainHeaderPath)
	if err != nil {
		return nil, fmt.Errorf("read header %s: %w", mainHeaderPath, err)
	}

	// 5. 使用 clang AST dump 提取函数签名
	functions, implementMacro, err := extractFunctionsWithClang(pkgDir, mainHeaderPath, string(headerContent), libType)
	if err != nil {
		return nil, fmt.Errorf("extract functions from %s: %w", libName, err)
	}

	return &LibAnalysisResult{
		Name:           libName,
		Type:           libType,
		Header:         mainHeader,
		Headers:        headers,
		ImplementMacro: implementMacro,
		Functions:      functions,
		Libraries:      libraries,
		IncludePath:    "../pkglib",
		LibraryPath:    "../pkglib/" + libName,
		AutoGenerated:  true,
		GeneratedAt:    time.Now().Format(time.RFC3339),
	}, nil
}

// extractFunctionsWithClang 使用 clang AST dump 提取函数签名
func extractFunctionsWithClang(pkgDir, mainHeaderPath, headerContent, libType string) (map[string]Function, string, error) {
	clangPath, err := findClangPath()
	if err != nil {
		return nil, "", fmt.Errorf("clang not found: %w", err)
	}

	// 检测 IMPLEMENTATION 宏
	implementMacro := detectImplementMacro(headerContent, filepath.Base(mainHeaderPath))

	// 检测并预定义常见导出宏
	extraDefines := detectCommonMacros(headerContent)

	// 检测并启用功能开关宏（如 NK_INCLUDE_*）
	includeMacros := detectIncludeMacros(headerContent)
	extraDefines = append(extraDefines, includeMacros...)

	// 构建 clang 命令
	args := []string{
		"-Xclang", "-ast-dump=json",
		"-fsyntax-only",
		// 添加 pkglib 父目录到 include 路径
		"-I", filepath.Dir(pkgDir),
	}
	// 添加预定义宏
	args = append(args, extraDefines...)

	// 单头文件库如果需要 IMPLEMENTATION 宏，在语法分析阶段不定义它
	// （只提取声明，不需要实现）

	args = append(args, mainHeaderPath)

	cmd := exec.Command(clangPath, args...)
	output, err := cmd.Output()
	if err != nil {
		// 如果带导出宏失败，尝试不带导出宏
		if len(extraDefines) > 0 {
			args2 := []string{
				"-Xclang", "-ast-dump=json",
				"-fsyntax-only",
				"-I", filepath.Dir(pkgDir),
				mainHeaderPath,
			}
			cmd2 := exec.Command(clangPath, args2...)
			output2, err2 := cmd2.Output()
			if err2 != nil {
				return nil, "", fmt.Errorf("clang ast-dump failed: %w\nstderr: %s", err, string(output))
			}
			output = output2
		} else {
			return nil, "", fmt.Errorf("clang ast-dump failed: %w", err)
		}
	}

	// 解析 AST JSON
	var astRoot ClangASTNode
	if err := json.Unmarshal(output, &astRoot); err != nil {
		return nil, "", fmt.Errorf("parse clang AST JSON: %w", err)
	}

	// 先提取 typedef 映射
	typedefs := extractTypedefs(&astRoot, mainHeaderPath)

	// 再提取函数声明（展开 typedef）
	functions := extractFunctionDecls(&astRoot, mainHeaderPath, typedefs)

	return functions, implementMacro, nil
}

// GenerateConfig 生成 JSON 配置文件
func (result *LibAnalysisResult) GenerateConfig() ([]byte, error) {
	type jsonFunction struct {
		Args    []string `json:"args"`
		VarArgs bool     `json:"varargs,omitempty"`
		Return  string   `json:"return"`
	}

	type jsonConfig struct {
		Name           string                  `json:"name"`
		Type           string                  `json:"type"`
		Header         string                  `json:"header"`
		Headers        []string                `json:"headers"`
		ImplementMacro string                  `json:"implement_macro,omitempty"`
		Libraries      []string                `json:"libraries,omitempty"`
		IncludePath    string                  `json:"include_path,omitempty"`
		LibraryPath    string                  `json:"library_path,omitempty"`
		Functions      map[string]jsonFunction `json:"functions"`
		AutoGenerated  bool                    `json:"auto_generated"`
		GeneratedAt    string                  `json:"generated_at"`
	}

	funcs := make(map[string]jsonFunction)
	for name, fn := range result.Functions {
		jf := jsonFunction{
			Args:    fn.Args,
			VarArgs: fn.VarArgs,
			Return:  fn.Return,
		}
		funcs[name] = jf
	}

	config := jsonConfig{
		Name:           result.Name,
		Type:           result.Type,
		Header:         result.Header,
		Headers:        result.Headers,
		ImplementMacro: result.ImplementMacro,
		Libraries:      result.Libraries,
		IncludePath:    result.IncludePath,
		LibraryPath:    result.LibraryPath,
		Functions:      funcs,
		AutoGenerated:  result.AutoGenerated,
		GeneratedAt:    result.GeneratedAt,
	}

	data, err := json.MarshalIndent(config, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal config: %w", err)
	}
	return data, nil
}

// WriteConfig 将分析结果写入 JSON 配置文件
func (result *LibAnalysisResult) WriteConfig(pkgDir string) error {
	data, err := result.GenerateConfig()
	if err != nil {
		return err
	}
	configPath := filepath.Join(pkgDir, result.Name+".json")
	return os.WriteFile(configPath, data, 0644)
}
