package stdlib

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

// ClangASTNode 表示 clang -ast-dump=json 输出的 AST 节点
type ClangASTNode struct {
	Kind         string         `json:"kind"`
	Name         string         `json:"name,omitempty"`
	Type         *ClangQualType `json:"type,omitempty"`
	Inner        []ClangASTNode `json:"inner,omitempty"`
	IsImplicit   bool           `json:"isImplicit,omitempty"`
	IsUsed       bool           `json:"isUsed,omitempty"`
	StorageClass string         `json:"storageClass,omitempty"`
	Loc          *ClangLoc      `json:"loc,omitempty"`
	Range        *ClangRange    `json:"range,omitempty"`
	MangledName  string         `json:"mangledName,omitempty"`
}

// ClangQualType 表示 clang AST 中的 qualType 字段
type ClangQualType struct {
	QualType string `json:"qualType"`
}

// ClangLoc 表示 clang AST 中的位置信息
type ClangLoc struct {
	File         string `json:"file,omitempty"`
	Line         int    `json:"line,omitempty"`
	Column       int    `json:"col,omitempty"`
	Offset       int    `json:"offset,omitempty"`
	IncludedFrom *struct {
		File string `json:"file"`
	} `json:"includedFrom,omitempty"`
}

// ClangRange 表示 clang AST 中的范围信息（含真实文件位置，loc 省略 file 时用于定位）
type ClangRange struct {
	Begin *ClangRangeLoc `json:"begin,omitempty"`
	End   *ClangRangeLoc `json:"end,omitempty"`
}

// ClangRangeLoc 表示范围端点位置（可含 spellingLoc/expansionLoc 完整定位）
type ClangRangeLoc struct {
	SpellingLoc  *ClangLoc `json:"spellingLoc,omitempty"`
	ExpansionLoc *ClangLoc `json:"expansionLoc,omitempty"`
	IncludedFrom *struct {
		File string `json:"file"`
	} `json:"includedFrom,omitempty"`
}

// resolveLocFile 解析节点声明的真实文件：
// loc.file → range.begin.expansionLoc（宏展开处=实际声明位置）
// → range.begin.spellingLoc（宏拼写处，<built-in> 等内置位置跳过）
// → 各层 includedFrom.file 兜底（clang 对同文件后续节点会省略 file 字段，
//    includedFrom 仍指向声明所在文件；全为空时推断与根文件同文件，返回 ""）
// 注意：不使用 loc.includedFrom——它指向的是包含链的根文件而非声明所在文件
func resolveLocFile(node *ClangASTNode) string {
	// 辅助：优先取 File，为空或内置位置时取 includedFrom
	pick := func(loc *ClangLoc) string {
		if loc == nil {
			return ""
		}
		if loc.File != "" && !strings.HasPrefix(loc.File, "<") {
			return loc.File
		}
		if loc.IncludedFrom != nil && !strings.HasPrefix(loc.IncludedFrom.File, "<") {
			return loc.IncludedFrom.File
		}
		return ""
	}
	if node.Loc != nil && node.Loc.File != "" {
		return node.Loc.File
	}
	if node.Range != nil && node.Range.Begin != nil {
		b := node.Range.Begin
		// 宏展开位置优先（函数由 CJSON_PUBLIC 等宏包裹时，
		// spellingLoc 指向宏定义处而 expansionLoc 指向真实声明处）
		if f := pick(b.ExpansionLoc); f != "" {
			return f
		}
		if f := pick(b.SpellingLoc); f != "" {
			return f
		}
		if b.IncludedFrom != nil && !strings.HasPrefix(b.IncludedFrom.File, "<") {
			return b.IncludedFrom.File
		}
	}
	return ""
}

// LibAnalysisResult 表示库分析结果
type LibAnalysisResult struct {
	Name           string
	Type           string   // "single_header" | "multi_header"
	Header         string   // 主头文件
	Headers        []string // 所有需要的头文件
	ImplementMacro string   // 如果需要 XXX_IMPLEMENTATION
	Functions      map[string]Function
	Libraries      []string // 需要链接的库
	IncludePath    string
	LibraryPath    string
	AutoGenerated  bool
	GeneratedAt    string
}

// findClangPath 查找 clang 可执行文件路径
func findClangPath() (string, error) {
	// 尝试直接查找
	if p, err := exec.LookPath("clang"); err == nil {
		return p, nil
	}
	// Windows 常见安装路径
	windowsPaths := []string{
		`D:\LLVM\bin\clang.exe`,
		`C:\LLVM\bin\clang.exe`,
		`C:\Program Files\LLVM\bin\clang.exe`,
	}
	for _, p := range windowsPaths {
		if _, err := os.Stat(p); err == nil {
			return p, nil
		}
	}
	return "", fmt.Errorf("clang not found in PATH or common locations")
}

// classifyLibrary 分类库是单头文件还是多头文件
func classifyLibrary(libDir string) (string, []string, error) {
	var headerFiles []string
	entries, err := os.ReadDir(libDir)
	if err != nil {
		return "", nil, err
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if strings.HasSuffix(name, ".h") || strings.HasSuffix(name, ".hpp") {
			// 跳过扩展 API 头（sqlite3ext.h / glext.h 等）：
			// 它们要求特殊的编译上下文（如 SQLITE_EXTENSION_INIT），不能作为普通头 include
			if strings.HasSuffix(strings.ToLower(name), "ext.h") {
				continue
			}
			headerFiles = append(headerFiles, name)
		}
	}
	if len(headerFiles) == 0 {
		return "", nil, fmt.Errorf("no header files found in %s", libDir)
	}
	if len(headerFiles) == 1 {
		return "single_header", headerFiles, nil
	}
	return "multi_header", headerFiles, nil
}

// scanLinkLibraries 扫描目录中的链接库文件
func scanLinkLibraries(libDir string) ([]string, string) {
	var libs []string
	var libPath string
	entries, err := os.ReadDir(libDir)
	if err != nil {
		return libs, libPath
	}
	libExts := map[string]bool{".a": true, ".lib": true, ".so": true, ".dll": true, ".dylib": true}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		ext := strings.ToLower(filepath.Ext(name))
		if libExts[ext] {
			// 去掉前缀 lib 和扩展名得到链接名
			base := name
			if strings.HasPrefix(base, "lib") && (ext == ".a" || ext == ".so" || ext == ".dylib") {
				base = base[3:]
			}
			base = strings.TrimSuffix(base, ext)
			// 去掉 .so 后面的版本号后缀
			if idx := strings.Index(base, ".so."); idx >= 0 {
				base = base[:idx]
			}
			libs = append(libs, base)
			libPath = libDir
		}
	}
	return libs, libPath
}

// detectImplementMacro 检测是否需要 XXX_IMPLEMENTATION 宏
func detectImplementMacro(headerContent string, headerName string) string {
	// 常见模式: #ifdef STB_IMAGE_IMPLEMENTATION / #define NK_IMPLEMENTATION
	upperName := strings.ToUpper(strings.TrimSuffix(headerName, filepath.Ext(headerName)))
	// 去掉路径前缀
	if idx := strings.LastIndex(upperName, "/"); idx >= 0 {
		upperName = upperName[idx+1:]
	}
	if idx := strings.LastIndex(upperName, "\\"); idx >= 0 {
		upperName = upperName[idx+1:]
	}
	// 替换非字母数字为下划线
	macroName := ""
	for _, c := range upperName {
		if (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') {
			macroName += string(c)
		} else {
			macroName += "_"
		}
	}
	candidate := macroName + "_IMPLEMENTATION"
	if strings.Contains(headerContent, candidate) {
		return candidate
	}
	return ""
}

// detectCommonMacros 检测常见的导出宏并返回需要预定义的宏
func detectCommonMacros(headerContent string) []string {
	var defines []string
	// 常见导出宏模式
	exportMacros := []struct {
		macro    string
		fallback string
	}{
		{"STBIDEF", "extern"},
		{"NK_API", "extern"},
		{"NK_LIB", "extern"},
		{"ZLIB_API", "extern"},
		{"ZEXPORT", "extern"},
		{"PNG_EXPORT", "extern"},
		{"CURL_EXTERN", "extern"},
		{"SQLITE_API", "extern"},
		{"XMLIMPORT", "extern"},
		{"XMLPARSEAPI", "extern"},
		{"_GLFWAPI", "extern"},
		{"GLAPI", "extern"},
		{"GLEWAPI", "extern"},
		{"SDL_EXPORT", "extern"},
		{"SDL_DECLSPEC", "extern"},
		{"FT_EXPORT", "extern"},
		{"FREETYPE_API", "extern"},
	}
	for _, m := range exportMacros {
		if strings.Contains(headerContent, m.macro) {
			defines = append(defines, fmt.Sprintf("-D%s=%s", m.macro, m.fallback))
		}
	}
	return defines
}

// detectIncludeMacros 检测头文件中的 XXX_INCLUDE_YYY 模式宏并自动启用
// 用于 nuklear 等高度可配置的单头文件库
func detectIncludeMacros(headerContent string) []string {
	var defines []string
	// 使用正则匹配 #ifdef XXX_INCLUDE_YYY 或 #if defined(XXX_INCLUDE_YYY) 模式
	// 提取宏名并自动启用
	seen := make(map[string]bool)

	// 匹配 #ifdef PREFIX_INCLUDE_SUFFIX 模式
	lines := strings.Split(headerContent, "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		// #ifdef MACRO_NAME
		if strings.HasPrefix(line, "#ifdef ") {
			macro := strings.TrimSpace(line[6:])
			if isIncludeMacro(macro) && !seen[macro] {
				seen[macro] = true
				defines = append(defines, "-D"+macro+"=1")
			}
		}
		// #ifndef 模式的反面（不启用）
		// #if defined(MACRO) 模式
		if strings.HasPrefix(line, "#if defined(") {
			// 提取括号内的宏名
			rest := line[len("#if defined("):]
			end := strings.Index(rest, ")")
			if end > 0 {
				macro := strings.TrimSpace(rest[:end])
				if isIncludeMacro(macro) && !seen[macro] {
					seen[macro] = true
					defines = append(defines, "-D"+macro+"=1")
				}
			}
		}
		// # if defined(MACRO) (带空格)
		if strings.HasPrefix(line, "# if defined(") {
			rest := line[len("# if defined("):]
			end := strings.Index(rest, ")")
			if end > 0 {
				macro := strings.TrimSpace(rest[:end])
				if isIncludeMacro(macro) && !seen[macro] {
					seen[macro] = true
					defines = append(defines, "-D"+macro+"=1")
				}
			}
		}
	}

	return defines
}

// isIncludeMacro 判断是否是 INCLUDE 类功能开关宏
func isIncludeMacro(macro string) bool {
	if strings.HasSuffix(macro, "_IMPLEMENTATION") {
		return false
	}
	if strings.Contains(macro, "_INCLUDE_") {
		return true
	}
	featurePatterns := []string{"_ENABLE", "_FEATURE", "_SUPPORT", "_USE_"}
	for _, pattern := range featurePatterns {
		if strings.Contains(macro, pattern) {
			return true
		}
	}
	return false
}

// isSystemFunction 判断是否是系统运行时函数（应跳过）
func isSystemFunction(name string) bool {
	systemPrefixes := []string{
		"__report_",
		"__security_",
		"__init_",
		"__va_",
		"_invalid_parameter_",
		"_invoke_watson",
		"_cexit",
		"_c_exit",
		"_exit",
		"_Exit",
		"_onexit",
		"_beginthread",
		"_endthread",
		"__stdcall",
		"__cdecl",
	}
	for _, prefix := range systemPrefixes {
		if strings.HasPrefix(name, prefix) {
			return true
		}
	}
	return false
}

// extractTypedefs 从 clang AST 中提取所有 typedef 映射
func extractTypedefs(node *ClangASTNode, sourceFile string) map[string]string {
	typedefs := make(map[string]string)
	extractTypedefsRecursive(node, sourceFile, typedefs)
	return typedefs
}

func extractTypedefsRecursive(node *ClangASTNode, sourceFile string, typedefs map[string]string) {
	if node.Kind == "TypedefDecl" && node.Name != "" && node.Type != nil {
		// 跳过隐式 typedef（编译器内部生成的）
		if node.IsImplicit {
			return
		}
		// 只提取来自目标文件或其包含文件的 typedef
		locFile := resolveLocFile(node)
		if locFile != "" {
			if strings.HasPrefix(locFile, "<") {
				return
			}
			if sourceFile != "" {
				locFileNorm := strings.ReplaceAll(locFile, "\\", "/")
				sourceNorm := strings.ReplaceAll(sourceFile, "\\", "/")
				if !strings.HasPrefix(locFileNorm, sourceNorm) &&
					!strings.Contains(locFileNorm, filepath.Dir(sourceNorm)) {
					return
				}
			}
		}
		typedefs[node.Name] = node.Type.QualType
	}
	for i := range node.Inner {
		extractTypedefsRecursive(&node.Inner[i], sourceFile, typedefs)
	}
}

// expandTypedefs 展开类型字符串中的 typedef 为底层类型
func expandTypedefs(typeStr string, typedefs map[string]string) string {
	result := typeStr
	// 最多迭代 10 次防止循环引用
	for i := 0; i < 10; i++ {
		changed := false
		for name, underlying := range typedefs {
			// 匹配 typedef 名称（作为完整标识符，不是其他类型名的一部分）
			// 模式: 空格或开头 + name + 空格/*/&/(/),/结尾
			newStr := replaceTypeToken(result, name, underlying)
			if newStr != result {
				result = newStr
				changed = true
			}
		}
		if !changed {
			break
		}
	}
	return result
}

// replaceTypeToken 替换类型字符串中的完整类型标识符
func replaceTypeToken(typeStr, oldTok, newTok string) string {
	// 简单实现：按 token 边界替换
	// 在 C 类型中，标识符边界通常是空格、*、&、(、)、,、const、restrict 等
	result := typeStr
	// 直接的子串替换可能导致部分匹配，但在实际库中 typedef 名通常有唯一前缀
	// 使用更精确的边界检查
	var builder strings.Builder
	i := 0
	for i < len(result) {
		// 尝试匹配 oldTok
		if i+len(oldTok) <= len(result) && result[i:i+len(oldTok)] == oldTok {
			// 检查前后是否是类型标识符边界
			beforeOK := (i == 0) || !isIdentChar(result[i-1])
			afterOK := (i+len(oldTok) >= len(result)) || !isIdentChar(result[i+len(oldTok)])
			if beforeOK && afterOK {
				builder.WriteString(newTok)
				i += len(oldTok)
				continue
			}
		}
		builder.WriteByte(result[i])
		i++
	}
	return builder.String()
}

// isIdentChar 检查字符是否是 C 标识符字符
func isIdentChar(c byte) bool {
	return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_'
}

// extractFunctionDecls 从 clang AST JSON 中递归提取函数声明
func extractFunctionDecls(node *ClangASTNode, sourceFile string, typedefs map[string]string, isCpp bool) map[string]Function {
	functions := make(map[string]Function)
	extractFunctionDeclsRecursive(node, sourceFile, functions, typedefs, isCpp)
	return functions
}

func extractFunctionDeclsRecursive(node *ClangASTNode, sourceFile string, functions map[string]Function, typedefs map[string]string, isCpp bool) {
	if node.Kind == "FunctionDecl" && node.Name != "" {
		if node.IsImplicit {
			return
		}
		// C++ 模式下的函数模板（如 template ImClamp）没有 mangledName，
		// 也没有对应的 C 链接符号，无法从 Kaula 生成的 C 代码调用，跳过
		if isCpp && node.MangledName == "" {
			return
		}
		// C++ 类方法/重载具有 mangled 名称（如 _ZN5ImGui4TextEPKcz），
		// 无法从 Kaula 生成的 C 代码按原名调用，跳过
		if node.MangledName != "" && node.MangledName != node.Name {
			return
		}
		// 位置过滤：只保留声明在目标头文件（或其所在目录）中的函数。
		// clang 的 JSON dump 对同文件后续节点会省略 loc.file，
		// 此时用 range 内的 spellingLoc/expansionLoc 定位真实文件；
		// 全部省略说明声明就在根文件本身，直接保留
		locFile := resolveLocFile(node)
		if locFile != "" {
			if strings.HasPrefix(locFile, "<") {
				return
			}
			if sourceFile != "" {
				locFileNorm := strings.ReplaceAll(locFile, "\\", "/")
				sourceNorm := strings.ReplaceAll(sourceFile, "\\", "/")
				if !strings.HasPrefix(locFileNorm, sourceNorm) &&
					!strings.Contains(locFileNorm, filepath.Dir(sourceNorm)) &&
					!strings.HasSuffix(locFileNorm, "/"+filepath.Base(sourceNorm)) &&
					!strings.HasSuffix(locFileNorm, "\\"+filepath.Base(sourceNorm)) {
					return
				}
			}
		}

		if isSystemFunction(node.Name) {
			return
		}

		fn := Function{
			Args:   extractParamTypes(node, typedefs),
			Return: extractReturnType(node, typedefs),
		}

		// 检测变参
		if node.Type != nil && strings.Contains(node.Type.QualType, ", ...") {
			fn.VarArgs = true
		}

		functions[node.Name] = fn
	}

	// 递归处理子节点
	for i := range node.Inner {
		extractFunctionDeclsRecursive(&node.Inner[i], sourceFile, functions, typedefs, isCpp)
	}
}

// extractReturnType 从 FunctionDecl 的 qualType 提取返回类型
func extractReturnType(node *ClangASTNode, typedefs map[string]string) string {
	if node.Type == nil {
		return "void"
	}
	qt := node.Type.QualType
	// 展开 typedef
	qt = expandTypedefs(qt, typedefs)
	// qualType 格式: "return_type (param_types)" 或 "return_type (param_types, ...)"
	idx := findFunctionParen(qt)
	if idx < 0 {
		return normalizeType(qt)
	}
	return normalizeType(strings.TrimSpace(qt[:idx]))
}

// extractParamTypes 从 FunctionDecl 的子节点 ParmVarDecl 提取参数类型
func extractParamTypes(node *ClangASTNode, typedefs map[string]string) []string {
	args := make([]string, 0)
	for i := range node.Inner {
		child := &node.Inner[i]
		if child.Kind == "ParmVarDecl" && child.Type != nil {
			t := child.Type.QualType
			t = expandTypedefs(t, typedefs)
			args = append(args, normalizeType(t))
		}
	}
	return args
}

// findFunctionParen 在 qualType 中找到函数参数的左括号位置
func findFunctionParen(qt string) int {
	depth := 0
	for i, c := range qt {
		if c == '<' {
			depth++
		} else if c == '>' {
			depth--
		} else if c == '(' && depth == 0 {
			return i
		}
	}
	return -1
}

// normalizeType 规范化 C 类型字符串
func normalizeType(typeStr string) string {
	t := strings.TrimSpace(typeStr)
	// 移除多余的空格
	replacements := []struct{ from, to string }{
		{"struct ", ""},
		{"enum ", ""},
		{"class ", ""},
		{"__ptr64", ""},
		{"__cdecl", ""},
		{"__stdcall", ""},
		{"__fastcall", ""},
		{"__thiscall", ""},
		{"__vectorcall", ""},
		{"WINAPI", ""},
		{"CALLBACK", ""},
		{"APIENTRY", ""},
	}
	for _, r := range replacements {
		t = strings.ReplaceAll(t, r.from, r.to)
	}
	// 规范化空格
	for strings.Contains(t, "  ") {
		t = strings.ReplaceAll(t, "  ", " ")
	}
	t = strings.TrimSpace(t)
	// 规范化指针风格: "char *" -> "char*"
	t = strings.ReplaceAll(t, " *", "*")
	t = strings.ReplaceAll(t, " &", "&")
	return t
}

// AnalyzePackage 分析指定包目录，生成配置
func AnalyzePackage(pkgDir string) (*LibAnalysisResult, error) {
	libName := filepath.Base(pkgDir)

	// 1. 分类单/多头文件
	libType, headerFiles, err := classifyLibrary(pkgDir)
	if err != nil {
		return nil, fmt.Errorf("classify library %s: %w", libName, err)
	}

	// 2. 扫描链接库
	libraries, _ := scanLinkLibraries(pkgDir)

	// 3. 选择主头文件并读取内容用于宏检测
	//    单头：唯一头文件；多头：优先与目录同名的头文件
	var mainHeader string
	if libType == "single_header" && len(headerFiles) == 1 {
		mainHeader = libName + "/" + headerFiles[0]
	} else {
		mainHeaderFound := false
		for _, h := range headerFiles {
			baseName := strings.TrimSuffix(h, filepath.Ext(h))
			if baseName == libName {
				mainHeader = libName + "/" + h
				mainHeaderFound = true
				break
			}
		}
		if !mainHeaderFound && len(headerFiles) > 0 {
			mainHeader = libName + "/" + headerFiles[0]
		}
	}

	// 4. 使用 clang AST dump 逐个头文件提取函数签名并合并
	//    多头文件库遍历所有顶层头文件；解析失败或提取不到函数的头
	//    （如 C++ 类头）自动跳过，只保留可被 C 代码调用的声明
	functions := make(map[string]Function)
	implementMacro := ""
	var effectiveHeaders []string
	var lastExtractErr error

	for _, h := range headerFiles {
		headerPath := filepath.Join(pkgDir, h)
		headerContent, rerr := os.ReadFile(headerPath)
		if rerr != nil {
			lastExtractErr = rerr
			continue
		}
		fns, mcr, usedCpp, cerr := extractFunctionsWithClang(pkgDir, headerPath, string(headerContent), libType)
		if cerr != nil {
			fmt.Printf("[Analyze] Skipping header %s: %v\n", h, cerr)
			lastExtractErr = cerr
			continue
		}
		if usedCpp {
			// C++ 模式才能解析的头文件无法被生成的 C 代码 #include，
			// 其中的 C 链接函数（如 extern "C" 包装）也无法获得声明，整体跳过
			fmt.Printf("[Analyze] Skipping C++ header %s (not C-compatible)\n", h)
			continue
		}
		if len(fns) > 0 {
			for name, fn := range fns {
				functions[name] = fn
			}
			effectiveHeaders = append(effectiveHeaders, h)
			if mcr != "" {
				implementMacro = mcr
			}
		}
	}

	if len(functions) == 0 {
		if lastExtractErr != nil {
			return nil, fmt.Errorf("extract functions from %s: %w", libName, lastExtractErr)
		}
		return nil, fmt.Errorf("no callable C functions found in %s headers", libName)
	}

	// 主头文件没有提取到函数时，用第一个成功提取的头文件作为主头
	if mainHeader != "" {
		mainBase := filepath.Base(mainHeader)
		mainHasFunctions := false
		for _, h := range effectiveHeaders {
			if h == mainBase {
				mainHasFunctions = true
				break
			}
		}
		if !mainHasFunctions && len(effectiveHeaders) > 0 {
			fmt.Printf("[Analyze] Main header %s yielded no functions, using %s (%d functions)\n", mainBase, effectiveHeaders[0], len(functions))
			mainHeader = libName + "/" + effectiveHeaders[0]
		}
	}

	// 5. 构建 headers 列表：只包含成功提取出函数的 C 兼容头文件
	//    （C++ 头无法被生成的 C 代码包含，已在上面跳过）
	var headers []string
	for _, h := range effectiveHeaders {
		headers = append(headers, fmt.Sprintf(`"%s/%s"`, libName, h))
	}

	return &LibAnalysisResult{
		Name:           libName,
		Type:           libType,
		Header:         mainHeader,
		Headers:        headers,
		ImplementMacro: implementMacro,
		Functions:      functions,
		Libraries:      libraries,
		// 使用绝对路径，避免相对路径随 clang 工作目录变化而失效
		IncludePath:    filepath.Dir(pkgDir),
		LibraryPath:    pkgDir,
		AutoGenerated:  true,
		GeneratedAt:    time.Now().Format(time.RFC3339),
	}, nil
}

// extractFunctionsWithClang 使用 clang AST dump 提取函数签名
// 返回函数表、IMPLEMENTATION 宏、是否使用了 C++ 模式解析
func extractFunctionsWithClang(pkgDir, mainHeaderPath, headerContent, libType string) (map[string]Function, string, bool, error) {
	clangPath, err := findClangPath()
	if err != nil {
		return nil, "", false, fmt.Errorf("clang not found: %w", err)
	}

	// 检测 IMPLEMENTATION 宏
	implementMacro := detectImplementMacro(headerContent, filepath.Base(mainHeaderPath))

	// 检测并预定义常见导出宏
	extraDefines := detectCommonMacros(headerContent)

	// 检测并启用功能开关宏（如 NK_INCLUDE_*）
	includeMacros := detectIncludeMacros(headerContent)
	extraDefines = append(extraDefines, includeMacros...)

	// 构建 clang 命令
	args := []string{
		"-Xclang", "-ast-dump=json",
		"-fsyntax-only",
		// 添加 pkglib 父目录到 include 路径
		"-I", filepath.Dir(pkgDir),
	}
	// 添加预定义宏
	args = append(args, extraDefines...)

	// 单头文件库如果需要 IMPLEMENTATION 宏，在语法分析阶段不定义它
	// （只提取声明，不需要实现）

	args = append(args, mainHeaderPath)

	cmd := exec.Command(clangPath, args...)
	cppMode := false
	output, err := cmd.Output()
	if err != nil && len(extraDefines) > 0 {
		// 如果带导出宏失败，尝试不带导出宏
		args2 := []string{
			"-Xclang", "-ast-dump=json",
			"-fsyntax-only",
			"-I", filepath.Dir(pkgDir),
			mainHeaderPath,
		}
		cmd2 := exec.Command(clangPath, args2...)
		output2, err2 := cmd2.Output()
		if err2 == nil {
			output = output2
			err = nil
		} else {
			output = output2
			err = err2
		}
	}
	if err != nil {
		// C 模式失败，可能是 C++ 头文件，重试 C++ 模式
		argsCpp := []string{
			"-Xclang", "-ast-dump=json",
			"-fsyntax-only",
			"-x", "c++",
			"-I", filepath.Dir(pkgDir),
			mainHeaderPath,
		}
		cmdCpp := exec.Command(clangPath, argsCpp...)
		outputCpp, errCpp := cmdCpp.Output()
		if errCpp != nil {
			return nil, "", false, fmt.Errorf("clang ast-dump failed (C and C++ modes): %v\nstderr: %s", err, string(outputCpp))
		}
		output = outputCpp
		cppMode = true
	}

	// 解析 AST JSON
	var astRoot ClangASTNode
	if err := json.Unmarshal(output, &astRoot); err != nil {
		return nil, "", false, fmt.Errorf("parse clang AST JSON: %w", err)
	}

	// 先提取 typedef 映射
	typedefs := extractTypedefs(&astRoot, mainHeaderPath)

	// 再提取函数声明（展开 typedef）
	functions := extractFunctionDecls(&astRoot, mainHeaderPath, typedefs, cppMode)

	return functions, implementMacro, cppMode, nil
}

// GenerateConfig 生成 JSON 配置文件
func (result *LibAnalysisResult) GenerateConfig() ([]byte, error) {
	type jsonFunction struct {
		Args    []string `json:"args"`
		VarArgs bool     `json:"varargs,omitempty"`
		Return  string   `json:"return"`
	}

	type jsonConfig struct {
		Name           string                  `json:"name"`
		Type           string                  `json:"type"`
		Header         string                  `json:"header"`
		Headers        []string                `json:"headers"`
		ImplementMacro string                  `json:"implement_macro,omitempty"`
		Libraries      []string                `json:"libraries,omitempty"`
		IncludePath    string                  `json:"include_path,omitempty"`
		LibraryPath    string                  `json:"library_path,omitempty"`
		Functions      map[string]jsonFunction `json:"functions"`
		AutoGenerated  bool                    `json:"auto_generated"`
		GeneratedAt    string                  `json:"generated_at"`
	}

	funcs := make(map[string]jsonFunction)
	for name, fn := range result.Functions {
		jf := jsonFunction{
			Args:    fn.Args,
			VarArgs: fn.VarArgs,
			Return:  fn.Return,
		}
		funcs[name] = jf
	}

	config := jsonConfig{
		Name:           result.Name,
		Type:           result.Type,
		Header:         result.Header,
		Headers:        result.Headers,
		ImplementMacro: result.ImplementMacro,
		Libraries:      result.Libraries,
		IncludePath:    result.IncludePath,
		LibraryPath:    result.LibraryPath,
		Functions:      funcs,
		AutoGenerated:  result.AutoGenerated,
		GeneratedAt:    result.GeneratedAt,
	}

	data, err := json.MarshalIndent(config, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal config: %w", err)
	}
	return data, nil
}

// WriteConfig 将分析结果写入 JSON 配置文件
func (result *LibAnalysisResult) WriteConfig(pkgDir string) error {
	data, err := result.GenerateConfig()
	if err != nil {
		return err
	}
	configPath := filepath.Join(pkgDir, result.Name+".json")
	return os.WriteFile(configPath, data, 0644)
}
